baseurl = "http://www.mactynow.ovh"
defaultcontentlanguage = "en"
languagecode = "en"
theme = "hugo-coder"
title = "mactynow"

paginate = 20

# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
author = "Charles Martinot"
avatarurl = "img/avatar.jpg"
description = "Charles' personal website"
info = "Backend and infrastructure engineer"
keywords = "blog,developer,personal"

faviconSVG = "/img/favicon.svg"
favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"

since = 2019

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

# Social links
[[params.social]]
icon = "fa-brands fa-github fa-2x"
name = "Github"
url = "https://github.com/mactynow/"
weight = 1
[[params.social]]
icon = "fa-brands fa-linkedin fa-2x"
name = "Linkedin"
url = "https://www.linkedin.com/in/charlesmartinot/"
weight = 2
[[params.social]]
icon = "fa-brands fa-mastodon fa-2x"
name = "Mastodon"
url = "https://mastodon.social/@mactynow"
weight = 3

# Menu links
# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url  = "posts/"
[[menu.main]]
name = "About"
url = "about/"
weight = 2
[[menu.main]]
name = "Experience"
url = "experience/"
weight = 2

[params.googleTagManager]
id = "G-FE83YX9P57"
